version: "3.8"

services:
  ke-enrichment:
    build: .
    container_name: ke_enrichment_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
