version: "3.8"

services:
  ke-enrichment:
    build: .
    container_name: ke_enrichment_app
    ports:
      - "5010:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - BUILDER_API_URL=
      - SPARQL_ENDPOINT=https://aopwiki.rdf.bigcat-bioinformatics.org/sparql/
